# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'sjazure-svcconnection'
    subscriptionId: '5034283a-8ee6-40ac-994e-4c7802788632'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'sjrg-devops'
    location: 'Japan East'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/SourajitSamadder/SJ1/master/sadeploy-copyfx-conditional.json'
    deploymentMode: 'Incremental'